TOP=..

include $(TOP)/configure/CONFIG

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#USR_CFLAGS += 

#=============================

# xxxRecord.h will be created from xxxRecord.dbd
#DBDINC += xxxRecord

#=============================

LIBRARY = drvUioPciGen
INC     = drvUioPciGen.h
# <name>.dbd will be created from <name>Include.dbd
DBD		= drvUioPciGen.dbd

drvUioPciGen_SRCS += drvUioPciGen.c

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
